# Generated by Django 5.2.8 on 2026-02-08 18:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APILog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(help_text='URL эндпоинта API', max_length=500, verbose_name='Эндпоинт')),
                ('method', models.CharField(help_text='HTTP метод запроса', max_length=10, verbose_name='HTTP метод')),
                ('status_code', models.IntegerField(help_text='HTTP статус код ответа', verbose_name='Статус код')),
                ('request_data', models.JSONField(blank=True, help_text='Данные отправленные в запросе', null=True, verbose_name='Данные запроса')),
                ('response_data', models.TextField(blank=True, help_text='Данные полученные в ответе', null=True, verbose_name='Данные ответа')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP адрес клиента', null=True, verbose_name='IP адрес')),
                ('user_agent', models.TextField(blank=True, help_text='User Agent клиента', null=True, verbose_name='User Agent')),
                ('created', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата запроса')),
                ('duration', models.FloatField(help_text='Время выполнения запроса в секундах', verbose_name='Длительность запроса (сек)')),
            ],
            options={
                'verbose_name': 'Лог API',
                'verbose_name_plural': 'Логи API',
                'ordering': ['-created'],
            },
        ),
    ]
