version: '3.8' 
 
services: 
  db: 
    image: postgres:13 
    container_name: foodgram_db
    environment: 
      POSTGRES_USER: ${POSTGRES_USER} 
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} 
      POSTGRES_DB: ${POSTGRES_DB}
    env_file: .env 
    volumes: 
      - pg_data:/var/lib/postgresql/data 
    networks: 
      - foodgram_network 
 
  backend: 
    image: arturioo22/foodgram_backend:latest 
    container_name: foodgram_backend 
    environment: 
      - DJANGO_SETTINGS_MODULE=foodgram_backend.settings 
    ports: 
      - "9001:9000" 
    volumes: 
      - static_volume:/app/collected_static 
      - media_volume:/app/media
      - ./.env:/app/.env
    depends_on: 
      - db 
    networks: 
      - foodgram_network 
 
  frontend: 
    image: arturioo22/foodgram_frontend:latest 
    container_name: foodgram_frontend 
    volumes: 
      - static_volume:/app/build 
    command: sh -c "cp -r /app/build/* /app/build/ && npx -y http-server -p 8000 /app/build" 
    networks: 
      - foodgram_network
 
  gateway: 
    image: arturioo22/foodgram_gateway:latest 
    container_name: foodgram_gateway 
    ports: 
      - "9000:80" 
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf 
      - static_volume:/static 
      - media_volume:/media 
    depends_on: 
      - backend 
      - frontend 
    networks: 
      - foodgram_network
 
volumes: 
  pg_data: 
  static_volume: 
  media_volume: 
 
networks: 
  foodgram_network: 
    driver: bridge