version: '3.8'

services:
  db:
    image: postgres:15
    container_name: foodgram_db_prod
    environment:
      POSTGRES_DB: ${DB_NAME:-foodgram}
      POSTGRES_USER: ${DB_USER:-foodgram_user}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-afdwMp-85pYexEuTJ27nLfLfxdw}
    volumes:
      - postgres_data_prod:/var/lib/postgresql/data
    networks:
      - foodgram_network_prod
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-foodgram_user} -d ${DB_NAME:-foodgram}"]
      interval: 30s
      timeout: 10s
      retries: 3

  backend:
    image: ${DOCKERHUB_USERNAME:-arturioo22}/foodgram_backend:latest
    container_name: foodgram_backend_prod
    environment:
      - DJANGO_SETTINGS_MODULE=foodgram.settings
      - DB_NAME=${DB_NAME:-foodgram}
      - DB_USER=${DB_USER:-foodgram_user}
      - DB_PASSWORD=${DB_PASSWORD:-afdwMp-85pYexEuTJ27nLfLfxdw}
      - DB_HOST=db
      - DB_PORT=5432
      - SECRET_KEY=${SECRET_KEY:--PpGq7VpK5vgk94e-7yTrL1soZMETDoUedrjnbvvPTkN6UrgAI6ViIIRsisFb1wfc5c}
      - DEBUG=${DEBUG:-False}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS:-fffoooddgramm.ddns.net,localhost,127.0.0.1,backend,frontend,gateway}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-http://fffoooddgramm.ddns.net,http://localhost,http://127.0.0.1}
      - CSRF_TRUSTED_ORIGINS=${CSRF_TRUSTED_ORIGINS:-http://fffoooddgramm.ddns.net,https://fffoooddgramm.ddns.net}
    volumes:
      - static_volume_prod:/app/collected_static
      - media_volume_prod:/app/media
    networks:
      - foodgram_network_prod
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy

  frontend:
    image: ${DOCKERHUB_USERNAME:-arturioo22}/foodgram_frontend:latest
    container_name: foodgram_frontend_prod
    environment:
      - REACT_APP_API_URL=/api
    networks:
      - foodgram_network_prod
    restart: unless-stopped

  gateway:
    image: ${DOCKERHUB_USERNAME:-arturioo22}/foodgram_gateway:latest
    container_name: foodgram_gateway_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static_volume_prod:/static
      - media_volume_prod:/media
    depends_on:
      - backend
      - frontend
    networks:
      - foodgram_network_prod
    restart: unless-stopped

volumes:
  postgres_data_prod:
  static_volume_prod:
  media_volume_prod:

networks:
  foodgram_network_prod:
    driver: bridge
