# Generated by Django 5.2.8 on 2026-02-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='follow',
            name='prevent_self_follow',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('author')), _negated=True), name='prevent_self_follow'),
        ),
    ]
