# Generated by Django 5.2.8 on 2026-02-22 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_follow_prevent_self_follow'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='follow',
            name='prevent_self_follow',
            constraint=models.CheckConstraint(condition=models.Q(('user', models.F('author')), _negated=True), name='prevent_self_follow', violation_error_message='Нельзя подписаться на самого себя.'),
        ),
    ]
